version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.8.3
    container_name: artifactory
    ports:
     - 8112:8081
    volumes:
     - ../../artifactory/data:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
    environment:
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
     - EXTRA_JAVA_OPTIONS=-Xmx2g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
