version: "2"
services:

  tomcat9ci_app:
    image: localhost:5000/tomcat9ci
    container_name: tomcat9ci_app
    environment:
      CATALINA_OPTS: "-Xmx2048m -Xms1024m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSClassUnloadingEnabled -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremoteport=364 -Dcom.sun.management.jmxremote.ssl=false"
    external_links:
      - mysql9ci
      - mssql9ci
    volumes:
      - ../../tomcat9ci_app/logs:/usr/local/tomcat/logs
      - ../../tomcat9ci_app/webapps:/usr/local/tomcat/webapps
      - ../../rootLocation:/var/9ci/rootLocation
      - ../../wars:/var/9ci/wars
    ports:
      - "8180:8080" # http port
      - "8280:8009" # ajp port

# Note:  The rootLocation is not rcm/rootLocation because that is defined for teamcity. The grails.serverURL
# will cause your local app to redirect there.
#
# Copy rcm/rootLocation over, make changes to rootLocation, jdbc connection, grails.serverURL and run from
# that.