version: "2"
services:

  tomcat9ci_99x:
    image: localhost:5000/tomcat9ci
    container_name: tomcat9ci_99x
    external_links:
      - mysql9ci
      - mssql9ci
    volumes:
      - ../../9.9.x/tomcat9ci_99x/logs:/usr/local/tomcat/logs
      - ../../9.9.x/tomcat9ci_99x/webapps:/usr/local/tomcat/webapps
      - ../../9.9.x/rootLocation:/var/9ci/rootLocation
    ports:
      - "8180:8080" # http port
      - "8280:8009" # ajp port

  tomcat9ci_993y:
    image: localhost:5000/tomcat9ci
    container_name: tomcat9ci_993y
    external_links:
      - mysql9ci
      - mssql9ci
    volumes:
      - ../../9.9.3.y/tomcat9ci_993y/logs:/usr/local/tomcat/logs
      - ../../9.9.3.y/tomcat9ci_993y/webapps:/usr/local/tomcat/webapps
      - ../../9.9.3.y/rootLocation:/var/9ci/rootLocation
    ports:
      - "8181:8080" # http port
      - "8281:8009" # ajp port

  tomcat9ci_100x:
    image: localhost:5000/tomcat9ci
    container_name: tomcat9ci_100x
    external_links:
      - mysql9ci
      - mssql9ci
    volumes:
      - ../../10.0.x/tomcat9ci_100x/logs:/usr/local/tomcat/logs
      - ../../10.0.x/tomcat9ci_100x/webapps:/usr/local/tomcat/webapps
      - ../../10.0.x/rootLocation:/var/9ci/rootLocation
    ports:
      - "8182:8080" # http port
      - "8282:8009" # ajp port

  tomcat9ci_ninecall:
    image: localhost:5000/tomcat9ci
    container_name: tomcat9ci_ninecall
    external_links:
      - mysql9ci
      - mssql9ci
    volumes:
      - ../../ninecall/tomcat9ci_ninecall/logs:/usr/local/tomcat/logs
      - ../../ninecall/tomcat9ci_ninecall/webapps:/usr/local/tomcat/webapps
      - ../../ninecall/rootLocation:/var/9ci/rootLocation
    ports:
      - "8183:8080" # http port
      - "8283:8009" # ajp port
